class RegisterPageLocators:
    url = "https://parabank.parasoft.com/parabank/register.htm"
    register="/html/body/div[1]/div[3]/div[1]/div/p[2]/a"
    first_name ="customer.firstName"
    last_name ="customer.lastName"
    address="customer.address.street"
    city="customer.address.city"
    state="customer.address.state"
    zipcode="customer.address.zipCode"
    phone ="customer.phoneNumber"
    ssn="customer.ssn"
    username="customer.username"
    password="customer.password"
    confirm_password="repeatedPassword"
    register_button = "/html/body/div[1]/div[3]/div[2]/form/table/tbody/tr[13]/td[2]/input"